train:
  data: G_21003_21008_21027_21032/G_21003_21008_21027_21032_Processed/names_clean.csv
  bucket: mlopsdemlbucket21032
  model_s3_folder: G_21003_21008_21027_21032/G_21003_21008_21027_21032_models
  model_s3_path: name_gender_model.pkl
  vectorizer_s3_path: name_gender_vectorizer.pkl
  random_state: 42
  max_iterations: 1000

aws:
  aws_access_key_id: ASIAVTUQT5TNIEACTY7K
  aws_secret_access_key: I9eDhuYgGWPJzepHQd3St5duojupjQN8v4AO0xPC
  region_name: eu-north-1

mlflow:
  MLFLOW_TRACKING_URI: http://13.61.196.51:5000/
